Remove gnuplot package and use conda
Remove gnuplot, in favor of installing it via conda.

Remove moose-tools requirement from all moose-dev-$ modules. However,
moose-tools will still be loading by default, due to gperf-tools
requirement in moose-dev-$ modules.

Create a gperf-tools advanced module so it can be loaded separately.

diff --git a/build_from_source/template/autojump b/build_from_source/template/autojump
--- a/build_from_source/template/autojump
+++ b/build_from_source/template/autojump
@@ -25,14 +25,19 @@ pre_run() {
     try_command 3 "git clone https://github.com/joelthelion/autojump.git"
     cd autojump
     if [ $? -ne 0 ]; then echo 'Failed to clone autojump repo'; cleanup 1; fi
-    git checkout fd287eab041f1677320a2f7a5e94bb601c2e706e
-    ./install.sh --local --bash --prefix "$PACKAGES_DIR/$PACKAGE"
+    git checkout 06e082c91805cb022900819b2e0881eeae780d58
+    ./install.py -f -d "$PACKAGES_DIR/$PACKAGE" -p "$PACKAGES_DIR/$PACKAGE"
+    if [ $? -ne 0 ]; then echo 'Failed to install autojump'; cleanup 1; fi
 }
 post_run() {
     cat <<EOF > "$PACKAGES_DIR/environments/autojump_profile"
-export PATH="$PACKAGES_DIR/autojump/bin":\$PATH
-export MANPATH="$PACKAGES_DIR/autojump/share/man:"\$MANPATH
-source "$PACKAGES_DIR/autojump/etc/profile.d/autojump.bash"
+if [ -f "$PACKAGES_DIR/autojump/share/autojump/autojump.\${MY_SHELL}" ]; then
+  export PATH="$PACKAGES_DIR/autojump/bin":\$PATH
+  export MANPATH="$PACKAGES_DIR/autojump/share/man:"\$MANPATH
+  source "$PACKAGES_DIR/autojump/share/autojump/autojump.\${MY_SHELL}"
+else
+  printf "Your current shell \${MY_SHELL}, is not supported by autojump\n"
+fi
 EOF
 }
 ##
