Iceream, RPM creation optimizations
Fix Icecream (use modified payload creator).
Delete seacas build directories (they are read only).
Speed up rpm creation.

diff --git a/build_from_source/template/icecream b/build_from_source/template/icecream
--- a/build_from_source/template/icecream
+++ b/build_from_source/template/icecream
@@ -78,7 +78,11 @@ post_run() {
     if [ $? -ne 0 ]; then echo 'Failed to build icecream'; cleanup 1; fi
     make install
     if [ $? -ne 0 ]; then echo 'Failed to install icecream'; cleanup 1; fi
-    if [ `uname` != "Darwin" ]; then
+    if [ `uname` = "Darwin" ]; then
+        PATH="$PACKAGES_DIR/icecream/bin:$PATH" icecc-create-env --clang "$PACKAGES_DIR/llvm-<LLVM>/bin/clang"
+        if [ $? -ne 0 ]; then echo 'Failed to create LLVM Icecream payload'; cleanup 1; fi
+        mv *.tar.gz "$PACKAGES_DIR/$PACKAGE/clang_<LLVM>.tar.gz"
+    else
        PATH="$PACKAGES_DIR/icecream/bin:$PATH" icecc-create-env --clang "$PACKAGES_DIR/llvm-<LLVM>/bin/clang" "$PACKAGES_DIR/llvm-<LLVM>/bin/clang++"
        if [ $? -ne 0 ]; then echo 'Failed to create LLVM Icecream payload'; cleanup 1; fi
        mv *.tar.gz "$PACKAGES_DIR/$PACKAGE/clang_<LLVM>.tar.gz"
