Maintenance release
Update icecream.
Use gold version of LLVM.
Clean minconda temp files.
Update Doxygen.

diff --git a/build_from_source/template/icecream_stack b/build_from_source/template/icecream_stack
--- a/build_from_source/template/icecream_stack
+++ b/build_from_source/template/icecream_stack
@@ -2,7 +2,7 @@
 #############
 ## Specifics
 ##
-DEP=(common_files modules gcc llvm)
+DEP=(common_files modules gcc llvm pkg-config)
 PACKAGE='icecream'
 
 #####
@@ -13,24 +13,24 @@ ARCH=(Darwin Linux)
 #####
 # Setting any of these variables to 'false' effectively skips that step
 # This is useful for items like 'autojump' which requires a git clone/checkout
-DOWNLOAD=(http://mooseframework.inl.gov/source_packages/libtool-2.4.6.tar.gz http://mooseframework.inl.gov/source_packages/lzo-2.09.tar.gz http://mooseframework.inl.gov/source_packages/libcap-ng-0.7.8.tar.gz http://mooseframework.inl.gov/source_packages/icecream-master.tar.gz)
+DOWNLOAD=(http://mooseframework.inl.gov/source_packages/libtool-2.4.6.tar.gz http://mooseframework.inl.gov/source_packages/lzo-2.09.tar.gz http://mooseframework.inl.gov/source_packages/libcap-ng-0.7.8.tar.gz http://mooseframework.inl.gov/source_packages/zstd-1.4.3.tar.gz http://mooseframework.inl.gov/source_packages/libarchive-3.4.0.tar.gz)
 EXTRACT='false'
 CONFIGURE="false"
 BUILD='false'
 INSTALL='false'
 
 pre_run() {
-    # Dependency packages that need to be built (but not distributed)
-    # So we will install these into the DOWNLOAD_DIR location which gets deleted when completed
-    if [ `uname` != 'Darwin' ]; then
-        ICECREAM_PACKAGES=(libtool-2.4.6.tar.gz lzo-2.09.tar.gz libcap-ng-0.7.8.tar.gz)
+    # Dependency packages that need to be built
+    if [ `uname` = 'Darwin' ]; then
+        ICECREAM_PACKAGES=(libtool-2.4.6.tar.gz lzo-2.09.tar.gz zstd-1.4.3.tar.gz libarchive-3.4.0.tar.gz)
     else
-        ICECREAM_PACKAGES=(libtool-2.4.6.tar.gz lzo-2.09.tar.gz)
+        ICECREAM_PACKAGES=(libtool-2.4.6.tar.gz lzo-2.09.tar.gz libcap-ng-0.7.8.tar.gz zstd-1.4.3.tar.gz libarchive-3.4.0.tar.gz)
     fi
 
+    mkdir -p "$PACKAGES_DIR/$PACKAGE/contribs"
     unset MODULEPATH
     source "$PACKAGES_DIR/Modules/init/bash"
-    module load advanced_modules autotools
+    module load advanced_modules autotools moose-tools
 
     for ICECREAM_PACKAGE in ${ICECREAM_PACKAGES[*]}; do
       target_dir=$(tar -tf "$DOWNLOAD_DIR/$ICECREAM_PACKAGE" | sed -e 's@/.*@@' | uniq)
@@ -39,28 +39,38 @@ pre_run() {
       if [ $? -ne 0 ]; then echo 'Failed to extract '$ICECREAM_PACKAGE; cleanup 1; fi
       cd $target_dir
       if [ $? -ne 0 ]; then echo "Failed to enter source directory $1/$target_dir"; cleanup 1; fi
-      ./configure --prefix="$1/install_deps/$target_dir"
-      if [ $? -ne 0 ]; then echo 'Failed to configure Icecream pacakge: '$ICECREAM_PACKAGE; cleanup 1; fi
-      make -j $MOOSE_JOBS
+      if [ -f 'configure' ]; then
+          ./configure --prefix="$PACKAGES_DIR/$PACKAGE/contribs/$target_dir"
+          if [ $? -ne 0 ]; then echo 'Failed to configure Icecream pacakge: '$ICECREAM_PACKAGE; cleanup 1; fi
+          make -j $MOOSE_JOBS
+      else
+          make prefix="$PACKAGES_DIR/$PACKAGE/contribs/$target_dir" -j $MOOSE_JOBS
+      fi
       if [ $? -ne 0 ]; then echo 'Failed to build Icecream pacakge: '$ICECREAM_PACKAGE; cleanup 1; fi
-      make install
+      if [ -f 'configure' ]; then
+          make install
+      else
+          make prefix="$PACKAGES_DIR/$PACKAGE/contribs/$target_dir" install
+      fi
       if [ $? -ne 0 ]; then echo 'Failed to install Icecream pacakge: '$ICECREAM_PACKAGE; cleanup 1; fi
-      if [ -d "$1/install_deps/$target_dir/lib64" ] && ! [ -d "$1/install_deps/$target_dir/lib" ]; then
-          ln -s "$1/install_deps/$target_dir/lib64" "$1/install_deps/$target_dir/lib"
+      if [ -d "$PACKAGES_DIR/$PACKAGE/contribs/$target_dir/lib/pkgconfig" ]; then
+          export PKG_CONFIG_PATH="$PACKAGES_DIR/$PACKAGE/contribs/$target_dir/lib/pkgconfig:$PKG_CONFIG_PATH"
+      fi
+      if [ -d "$PACKAGES_DIR/$PACKAGE/contribs/$target_dir/lib64" ] && ! [ -d "$PACKAGES_DIR/$PACKAGE/contribs/$target_dir/lib" ]; then
+          ln -s "$PACKAGES_DIR/$PACKAGE/contribs/$target_dir/lib64" "$PACKAGES_DIR/$PACKAGE/contribs/$target_dir/lib"
       fi
     done
 }
 post_run() {
     cd $1
-    tar -xf "$DOWNLOAD_DIR/icecream-master.tar.gz" -C .
-    if [ $? -ne 0 ]; then echo 'Failed to extract icecream-master.tar.gz'; cleanup 1; fi
-    cd $(tar -tf "$DOWNLOAD_DIR/icecream-master.tar.gz" | sed -e 's@/.*@@' | uniq)
-    if [ $? -ne 0 ]; then echo 'Failed to enter source directory '$(tar -tf "$DOWNLOAD_DIR/icecream-master.tar.gz" | sed -e 's@/.*@@' | uniq | cut -d. -f 2); cleanup 1; fi
-    PATH="$1/install_deps/libtool-2.4.6/bin:$PATH" ./autogen.sh
-    if [ `uname` != 'Darwin' ]; then
-        LDFLAGS="-L$1/install_deps/lzo-2.09/lib -llzo2 -L$1/install_deps/libcap-ng-0.7.8/lib -lcap-ng" CPPFLAGS="-I$1/install_deps/libcap-ng-0.7.8/include -I$1/install_deps/lzo-2.09/include" ./configure --prefix="$PACKAGES_DIR/$PACKAGE" --without-man
+    git clone https://github.com/icecc/icecream.git
+    cd icecream
+    git checkout 1.3
+    PATH="$PACKAGES_DIR/$PACKAGE/contribs/libtool-2.4.6/bin:$PATH" ./autogen.sh
+    if [ `uname` = 'Darwin' ]; then
+        LDFLAGS="-L$PACKAGES_DIR/$PACKAGE/contribs/lzo-2.09/lib -llzo2 `pkg-config libzstd libarchive --libs`" CPPFLAGS="-I$PACKAGES_DIR/$PACKAGE/contribs/lzo-2.09/include `pkg-config libzstd libarchive --cflags`" CFLAGS="`pkg-config libzstd libarchive --cflags`" ./configure --prefix="$PACKAGES_DIR/$PACKAGE" --without-man
     else
-        LDFLAGS="-L$1/install_deps/lzo-2.09/lib -llzo2" CPPFLAGS="-I$1/install_deps/lzo-2.09/include" ./configure --prefix="$PACKAGES_DIR/$PACKAGE" --without-man
+        LDFLAGS="-L$PACKAGES_DIR/$PACKAGE/contribs/lzo-2.09/lib -llzo2 -L$PACKAGES_DIR/$PACKAGE/contribs/libcap-ng-0.7.8/lib -lcap-ng" CPPFLAGS="-I$PACKAGES_DIR/$PACKAGE/contribs/libcap-ng-0.7.8/include -I$PACKAGES_DIR/$PACKAGE/contribs/lzo-2.09/include" ./configure --prefix="$PACKAGES_DIR/$PACKAGE" --without-man
     fi
 
     if [ $? -ne 0 ]; then echo 'Failed to configure icecream'; cleanup 1; fi
@@ -68,17 +78,17 @@ post_run() {
     if [ $? -ne 0 ]; then echo 'Failed to build icecream'; cleanup 1; fi
     make install
     if [ $? -ne 0 ]; then echo 'Failed to install icecream'; cleanup 1; fi
-    if [ `uname` != 'Darwin' ]; then
+    if [ `uname` = 'Darwin' ]; then
+        PATH="$PACKAGES_DIR/icecream/bin:$PATH" icecc-create-env --clang "$PACKAGES_DIR/llvm-<LLVM>/bin/clang"
+        if [ $? -ne 0 ]; then echo 'Failed to create LLVM Icecream payload'; cleanup 1; fi
+        mv *.tar.gz "$PACKAGES_DIR/$PACKAGE/clang_<LLVM>.tar.gz"
+    else
         PATH="$PACKAGES_DIR/icecream/bin:$PATH" icecc-create-env --clang "$PACKAGES_DIR/llvm-<LLVM>/bin/clang" "$PACKAGES_DIR/llvm-<LLVM>/bin/clang++"
         if [ $? -ne 0 ]; then echo 'Failed to create LLVM Icecream payload'; cleanup 1; fi
         mv *.tar.gz "$PACKAGES_DIR/$PACKAGE/clang_<LLVM>.tar.gz"
         PATH="$PACKAGES_DIR/icecream/bin:$PATH" icecc-create-env --gcc "$PACKAGES_DIR/<GCC>/bin/gcc" "$PACKAGES_DIR/<GCC>/bin/g++"
         if [ $? -ne 0 ]; then echo 'Failed to create GCC Icecream payload'; cleanup 1; fi
         mv *.tar.gz "$PACKAGES_DIR/$PACKAGE/<GCC>.tar.gz"
-    else
-        PATH="$PACKAGES_DIR/icecream/bin:$PATH" icecc-create-env --clang "$PACKAGES_DIR/llvm-<LLVM>/bin/clang"
-        if [ $? -ne 0 ]; then echo 'Failed to create LLVM Icecream payload'; cleanup 1; fi
-        mv *.tar.gz "$PACKAGES_DIR/$PACKAGE/clang_<LLVM>.tar.gz"
     fi
     cd "$PACKAGES_DIR/$PACKAGE/libexec/icecc/bin"
     ln -s "$PACKAGES_DIR/$PACKAGE/bin/icecc" clang
