Syntax and Build fixes
Do not build GCC/Clang with CCACHE enabled. This seems to break
Darwin targets when building anything requires clang to link to
fortran objects.

Fix module load typo in petsc-default-mpich-clang-opt.

Fix icecream_stack; OpenSUSE insists on making lib64 directories.

Add ability to override jobs when running scripts interactively.

Closes #114 #115

diff --git a/build_from_source/template/icecream_stack b/build_from_source/template/icecream_stack
--- a/build_from_source/template/icecream_stack
+++ b/build_from_source/template/icecream_stack
@@ -33,17 +33,21 @@ pre_run() {
     module load advanced_modules autotools
 
     for ICECREAM_PACKAGE in ${ICECREAM_PACKAGES[*]}; do
+      target_dir=$(tar -tf $DOWNLOAD_DIR/$ICECREAM_PACKAGE | sed -e 's@/.*@@' | uniq)
       cd $1
       tar -xf $DOWNLOAD_DIR/$ICECREAM_PACKAGE -C .
       if [ $? -ne 0 ]; then echo 'Failed to extract '$ICECREAM_PACKAGE; cleanup 1; fi
-      cd $(tar -tf $DOWNLOAD_DIR/$ICECREAM_PACKAGE | sed -e 's@/.*@@' | uniq)
-      if [ $? -ne 0 ]; then echo 'Failed to enter source directory '$(tar -tf $DOWNLOAD_DIR/$ICECREAM_PACKAGE | sed -e 's@/.*@@' | uniq); cleanup 1; fi
-      ./configure --prefix=$1/install_deps/$(tar -tf $DOWNLOAD_DIR/$ICECREAM_PACKAGE | sed -e 's@/.*@@' | uniq)
+      cd $target_dir
+      if [ $? -ne 0 ]; then echo "Failed to enter source directory $1/$target_dir"; cleanup 1; fi
+      ./configure --prefix=$1/install_deps/$target_dir
       if [ $? -ne 0 ]; then echo 'Failed to configure Icecream pacakge: '$ICECREAM_PACKAGE; cleanup 1; fi
       make -j $MOOSE_JOBS
       if [ $? -ne 0 ]; then echo 'Failed to build Icecream pacakge: '$ICECREAM_PACKAGE; cleanup 1; fi
       make install
       if [ $? -ne 0 ]; then echo 'Failed to install Icecream pacakge: '$ICECREAM_PACKAGE; cleanup 1; fi
+      if [ -d $1/install_deps/$target_dir/lib64 ] && ! [ -d $1/install_deps/$target_dir/lib ]; then
+          ln -s $1/install_deps/$target_dir/lib64 $1/install_deps/$target_dir/lib
+      fi
     done
 }
 post_run() {
