OpenMPI does not seem to build with load balancing

diff --git a/build_from_source/template/openmpi-gcc b/build_from_source/template/openmpi-gcc
--- a/build_from_source/template/openmpi-gcc
+++ b/build_from_source/template/openmpi-gcc
@@ -4,6 +4,7 @@
 ##
 DEP=(modules gcc)
 PACKAGE='openmpi-gcc'
+SERIAL=True
 
 #####
 # Set the operating system allowed to build this module
@@ -15,20 +16,31 @@ ARCH=(Darwin Linux)
 # This is useful for items like 'autojump' which requires a git clone/checkout
 DOWNLOAD='http://mooseframework.org/source_packages/<OPENMPI>.tar.gz'
 EXTRACT='<OPENMPI>.tar.gz'
-CONFIGURE="../configure --prefix=$PACKAGES_DIR/openmpi/<OPENMPI>/gcc-opt \
-CC=gcc CXX=g++ FC=gfortran F77=gfortran \
-CFLAGS='' CXXFLAGS='' FFLAGS='' FCFLAGS='' F77FLAGS=''"
-BUILD='true'
+CONFIGURE="false"
+BUILD='false'
 INSTALL='true'
 
 pre_run() {
     if [ -d $PACKAGES_DIR/openmpi/<OPENMPI>/gcc-opt ]; then
 	rm -rf $PACKAGES_DIR/openmpi/<OPENMPI>/gcc-opt
     fi
-    mkdir gcc-opt; cd gcc-opt
     unset MODULEPATH
     source $PACKAGES_DIR/Modules/<MODULES>/init/bash
     module load advanced_modules gcc
+
+    # Build and enter out-of-tree directory
+    mkdir gcc-opt; cd gcc-opt
+
+    # Configure
+    ../configure --prefix=$PACKAGES_DIR/openmpi/<OPENMPI>/gcc-opt \
+CC=gcc CXX=g++ FC=gfortran F77=gfortran \
+CFLAGS='' CXXFLAGS='' FFLAGS='' FCFLAGS='' F77FLAGS=''
+    if [ $? -ne 0 ]; then echo "Failed to configure $PACKAGE"; cleanup 1; fi
+
+    # Make serially
+    make -j 1
+    if [ $? -ne 0 ]; then echo "Failed to make $1"; cleanup 1; fi
+
 }
 post_run() {
     cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose/.<OPENMPI>_gcc
