Change PETSc identifiers to better describe our stable (default) vs alternate (usually newer). This allows PETSc 3.7 to be apart of the package but not necessarily the default our end-users will be loading. No need for rpath in later versions of PETSc. Rename the actual module file.

diff --git a/build_from_source/template/petsc-default-mpich-gcc b/build_from_source/template/petsc-default-mpich-gcc
--- a/build_from_source/template/petsc-default-mpich-gcc
+++ b/build_from_source/template/petsc-default-mpich-gcc
@@ -3,7 +3,7 @@
 ## Specifics
 ##
 DEP=(modules cmake gcc mpich-gcc)
-PACKAGE='<PETSC_NEW>-mpich-gcc'
+PACKAGE='<PETSC_DEFAULT>-mpich-gcc'
 
 #####
 # Set the operating system allowed to build this module
@@ -13,10 +13,10 @@ ARCH=(Darwin Linux)
 #####
 # Setting any of these variables to 'false' effectively skips that step
 # This is useful for items like 'autojump' which requires a git clone/checkout
-DOWNLOAD='http://mooseframework.org/source_packages/<PETSC_NEW>.tar.gz'
-EXTRACT='<PETSC_NEW>.tar.gz'
+DOWNLOAD='http://mooseframework.org/source_packages/<PETSC_DEFAULT>.tar.gz'
+EXTRACT='<PETSC_DEFAULT>.tar.gz'
 CONFIGURE="./configure \
---prefix=$PACKAGES_DIR/petsc/mpich_<PETSC_NEW>/gcc-opt-superlu \
+--prefix=$PACKAGES_DIR/petsc/mpich_<PETSC_DEFAULT>/gcc-opt-superlu \
 --download-hypre=1 \
 --with-ssl=0 \
 --with-debugging=no \
@@ -43,8 +43,8 @@ BUILD='false'
 INSTALL='false'
 
 pre_run() {
-    if [ -d $PACKAGES_DIR/petsc/mpich_<PETSC_NEW>/gcc-opt-superlu ]; then
-	rm -rf $PACKAGES_DIR/petsc/mpich_<PETSC_NEW>/gcc-opt-superlu
+    if [ -d $PACKAGES_DIR/petsc/mpich_<PETSC_DEFAULT>/gcc-opt-superlu ]; then
+	rm -rf $PACKAGES_DIR/petsc/mpich_<PETSC_DEFAULT>/gcc-opt-superlu
     fi
     unset MODULEPATH
     source $PACKAGES_DIR/Modules/<MODULES>/init/bash
@@ -53,29 +53,28 @@ pre_run() {
 
 post_run() {
     if [ `uname` = "Darwin" ]; then
-	make PETSC_DIR=$1/<PETSC_NEW> PETSC_ARCH=arch-darwin-c-opt all
-	if [ $? -ne 0 ]; then echo "Error while building PETSc"; cleanup 1; fi
-	make PETSC_DIR=$1/<PETSC_NEW> PETSC_ARCH=arch-darwin-c-opt install
-	if [ $? -ne 0 ]; then echo "Error while installing PETSc"; cleanup 1; fi
+	    make PETSC_DIR=$1/<PETSC_DEFAULT> PETSC_ARCH=arch-darwin-c-opt all
+	    if [ $? -ne 0 ]; then echo "Error while building PETSc"; cleanup 1; fi
+	    make PETSC_DIR=$1/<PETSC_DEFAULT> PETSC_ARCH=arch-darwin-c-opt install
+	    if [ $? -ne 0 ]; then echo "Error while installing PETSc"; cleanup 1; fi
     else
-	make PETSC_DIR=$1/<PETSC_NEW> PETSC_ARCH=arch-linux2-c-opt all
-	if [ $? -ne 0 ]; then echo "Error while building PETSc"; cleanup 1; fi
-	make PETSC_DIR=$1/<PETSC_NEW> PETSC_ARCH=arch-linux2-c-opt install
-	if [ $? -ne 0 ]; then echo "Error while installing PETSc"; cleanup 1; fi
+	    make PETSC_DIR=$1/<PETSC_DEFAULT> PETSC_ARCH=arch-linux2-c-opt all
+	    if [ $? -ne 0 ]; then echo "Error while building PETSc"; cleanup 1; fi
+	    make PETSC_DIR=$1/<PETSC_DEFAULT> PETSC_ARCH=arch-linux2-c-opt install
+	    if [ $? -ne 0 ]; then echo "Error while installing PETSc"; cleanup 1; fi
     fi
-    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose/.mpich_<PETSC_NEW>-gcc
+    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose/.mpich_<PETSC_DEFAULT>-gcc
 #%Module1.0#####################################################################
 ##
-## MPICH GCC <PETSC_NEW> superlu modulefile
+## MPICH GCC <PETSC_DEFAULT> superlu modulefile
 ##
 ##
 ##
 set         BASE_PATH        $PACKAGES_DIR
-setenv      PETSC_DIR        \$BASE_PATH/petsc/mpich_<PETSC_NEW>/gcc-opt-superlu
+setenv      PETSC_DIR        \$BASE_PATH/petsc/mpich_<PETSC_DEFAULT>/gcc-opt-superlu
 EOF
     cd $PACKAGES_DIR/Modules/<MODULES>/mpich_gcc
-    ln -s ../modulefiles/moose/.mpich_<PETSC_NEW>-gcc <PETSC_NEW>
-
+    ln -s ../modulefiles/moose/.mpich_<PETSC_DEFAULT>-gcc <PETSC_DEFAULT>
 }
 
 ##
