When building on Dawrin machines, use system blas instead of PETSc supplied (downloaded) version.

diff --git a/build_from_source/template/petsc-default-openmpi-gcc b/build_from_source/template/petsc-default-openmpi-gcc
--- a/build_from_source/template/petsc-default-openmpi-gcc
+++ b/build_from_source/template/petsc-default-openmpi-gcc
@@ -15,7 +15,43 @@ ARCH=(Darwin Linux)
 # This is useful for items like 'autojump' which requires a git clone/checkout
 DOWNLOAD='http://mooseframework.org/source_packages/<PETSC_DEFAULT>.tar.gz'
 EXTRACT='<PETSC_DEFAULT>.tar.gz'
-CONFIGURE="./configure \
+CONFIGURE="false"
+BUILD='false'
+INSTALL='false'
+
+pre_run() {
+    if [ -d $PACKAGES_DIR/petsc/openmpi_<PETSC_DEFAULT>/gcc-opt-superlu ]; then
+	rm -rf $PACKAGES_DIR/petsc/openmpi_<PETSC_DEFAULT>/gcc-opt-superlu
+    fi
+    unset MODULEPATH
+    source $PACKAGES_DIR/Modules/<MODULES>/init/bash
+    module load advanced_modules cmake openmpi-gcc
+    if [ `uname` = "Darwin" ]; then
+	./configure \
+--prefix=$PACKAGES_DIR/petsc/openmpi_<PETSC_DEFAULT>/gcc-opt-superlu \
+--download-hypre=1 \
+--with-ssl=0 \
+--with-debugging=no \
+--with-pic=1 \
+--with-shared-libraries=1 \
+--with-cc=mpicc \
+--with-cxx=mpicxx \
+--with-fc=mpif90 \
+--with-blas-lapack-dir=/usr/lib \
+--download-metis=1 \
+--download-parmetis=1 \
+--download-superlu_dist=1 \
+--download-mumps=1 \
+--download-scalapack=1 \
+-CC=mpicc -CXX=mpicxx -FC=mpif90 -F77=mpif77 -F90=mpif90 \
+-CFLAGS='-fPIC -fopenmp' \
+-CXXFLAGS='-fPIC -fopenmp' \
+-FFLAGS='-fPIC -fopenmp' \
+-FCFLAGS='-fPIC -fopenmp' \
+-F90FLAGS='-fPIC -fopenmp' \
+-F77FLAGS='-fPIC -fopenmp'
+    else
+	./configure \
 --prefix=$PACKAGES_DIR/petsc/openmpi_<PETSC_DEFAULT>/gcc-opt-superlu \
 --download-hypre=1 \
 --with-ssl=0 \
@@ -37,33 +73,22 @@ CONFIGURE="./configure \
 -FFLAGS='-fPIC -fopenmp' \
 -FCFLAGS='-fPIC -fopenmp' \
 -F90FLAGS='-fPIC -fopenmp' \
--F77FLAGS='-fPIC -fopenmp'"
-
-BUILD='false'
-INSTALL='false'
-
-pre_run() {
-    if [ -d $PACKAGES_DIR/petsc/openmpi_<PETSC_DEFAULT>/gcc-opt-superlu ]; then
-	rm -rf $PACKAGES_DIR/petsc/openmpi_<PETSC_DEFAULT>/gcc-opt-superlu
+-F77FLAGS='-fPIC -fopenmp'
     fi
-    unset MODULEPATH
-    source $PACKAGES_DIR/Modules/<MODULES>/init/bash
-    module load advanced_modules cmake openmpi-gcc
 }
 
 post_run() {
     if [ `uname` = "Darwin" ]; then
-	    make PETSC_DIR=$1/<PETSC_DEFAULT> PETSC_ARCH=arch-darwin-c-opt all
-	    if [ $? -ne 0 ]; then echo "Error while building PETSc"; cleanup 1; fi
-	    make PETSC_DIR=$1/<PETSC_DEFAULT> PETSC_ARCH=arch-darwin-c-opt install
-	    if [ $? -ne 0 ]; then echo "Error while installing PETSc"; cleanup 1; fi
+	make PETSC_DIR=$1/<PETSC_DEFAULT> PETSC_ARCH=arch-darwin-c-opt all
+	if [ $? -ne 0 ]; then echo "Error while building PETSc"; cleanup 1; fi
+	make PETSC_DIR=$1/<PETSC_DEFAULT> PETSC_ARCH=arch-darwin-c-opt install
+	if [ $? -ne 0 ]; then echo "Error while installing PETSc"; cleanup 1; fi
     else
-	    make PETSC_DIR=$1/<PETSC_DEFAULT> PETSC_ARCH=arch-linux2-c-opt all
-	    if [ $? -ne 0 ]; then echo "Error while building PETSc"; cleanup 1; fi
-	    make PETSC_DIR=$1/<PETSC_DEFAULT> PETSC_ARCH=arch-linux2-c-opt install
-	    if [ $? -ne 0 ]; then echo "Error while installing PETSc"; cleanup 1; fi
+	make PETSC_DIR=$1/<PETSC_DEFAULT> PETSC_ARCH=arch-linux2-c-opt all
+	if [ $? -ne 0 ]; then echo "Error while building PETSc"; cleanup 1; fi
+	make PETSC_DIR=$1/<PETSC_DEFAULT> PETSC_ARCH=arch-linux2-c-opt install
+	if [ $? -ne 0 ]; then echo "Error while installing PETSc"; cleanup 1; fi
     fi
-
     cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose/.openmpi_<PETSC_DEFAULT>-gcc
 #%Module1.0#####################################################################
 ##
