Use LLVM 6.0.1
Revert to LLVM 6.0.1. We are unable to build PETSc 3.8.3 with latest LLVM.

Modify all civet-related petsc targets to load miniconda. Miniconda was
being loaded by moose-tools previously.

Correct the try_again function (convert it to an array). The function was
not detecting anything except the last command run.

diff --git a/build_from_source/functions b/build_from_source/functions
--- a/build_from_source/functions
+++ b/build_from_source/functions
@@ -48,20 +48,24 @@ try_command() {
     allowed_count=$1
     command_string="$2"
     try_count=0
+    IFS=';' read -r -a command_array <<< "$command_string"
     while [ "$try_count" -lt "$allowed_count" ]; do
         let try_count=try_count+1
-        eval "$command_string"
-        retcode=$?
-        if [ "$retcode" != "0" ] && [ $try_count = $allowed_count ]; then
-            echo "Failed $1 times, trying to execute: $command_string"
-            cleanup 1
-        elif [ "$retcode" != "0" ]; then
-            sleep 30
-        else
-            break
+        error_count=0
+        for command in "${command_array[@]}"; do
+            eval $command
+            let error_count+=$?
+        done
+        if test $error_count -eq 0; then
+            TRYING="FALSE"
+            return
         fi
+        # There was an error. Rest a moment before trying again
+        sleep 10
     done
     TRYING="FALSE"
+    echo -e "\n\n\n#############\nFailed $allowed_count times, trying to execute: $command_string"
+    cleanup 1
 }
 
 pause() {
