Work with a DAG
Use a DAG object to control what gets built.

diff --git a/build_from_source/functions b/build_from_source/functions
--- a/build_from_source/functions
+++ b/build_from_source/functions
@@ -194,7 +194,7 @@ cleanup() {
     else
         echo "Error while working on: $PACKAGE located at: $src_temp"
     fi
-        exit $1
+    exit $1
 }
 
 umask 022
@@ -204,34 +204,38 @@ for OPERATING_SYSTEM in ${ARCH[*]}; do
     if [ "$OPERATING_SYSTEM" = `uname` ]; then CONTINUE="true"; fi
 done
 PROGRESS="$RELATIVE_DIR/progress"
-if ! [ -f "$PROGRESS" ]; then touch "$PROGRESS"; fi
-if [ "$CONTINUE" = "true" ]; then
-    error=""
-    for dependency in ${DEP[*]}; do
-        if [ `grep -ci ^$dependency $PROGRESS` -eq 0 ]; then
-            error+=$dependency' '
+touch $PROGRESS
+if [ `grep -c $ME $PROGRESS` -eq 0 ]; then
+    if ! [ -f "$PROGRESS" ]; then touch "$PROGRESS"; fi
+    if [ "$CONTINUE" = "true" ]; then
+        error=""
+        for dependency in ${DEP[*]}; do
+            if [ `grep -ci ^$dependency $PROGRESS` -eq 0 ]; then
+                error+=$dependency' '
+            fi
+        done
+        if ! [ -z "$error" ]; then
+            echo -e "\nDependencies not met: $error"
+            exit 0
         fi
-    done
-    if ! [ -z "$error" ]; then
-        echo -e "\nDependencies not met: $error"
-        exit 0
-    fi
-    if [ "$DOWNLOAD_ONLY" == "True" ]; then
-      download
+        if [ "$DOWNLOAD_ONLY" == "True" ]; then
+            download
+        else
+            export src_temp="$TEMP_PREFIX/$PACKAGE"
+            clean_attempt
+            download
+            extract
+            pre_run "$src_temp"
+            configure
+            build
+            make_install
+            post_run "$src_temp"
+        fi
+        echo $ME >> $PROGRESS
+        cleanup 0
     else
-      export src_temp="$TEMP_PREFIX/$PACKAGE"
-      clean_attempt
-      download
-      extract
-      pre_run "$src_temp"
-      configure
-      build
-      make_install
-      post_run "$src_temp"
+        echo -e "This platform does not support $PACKAGE"
+        echo "$ME n/a" >> "$PROGRESS"
     fi
-    echo $ME >> $PROGRESS
-    cleanup 0
-else
-    echo -e "This platform does not support $PACKAGE"
-    echo "$ME n/a" >> "$PROGRESS"
+    echo -e "$ME previously built"
 fi
